### ISSUE TITLE
You don't die when you fall off screen

### ISSUE THREAD

**Issue by chadium** [phpgl/flappyphpant#5]
If you fall off screen after pressing space to start, the game will keep going. You do not die. You will, in fact, win with this strategy.

I happened to catch this on video, It happens somewhere at the 11:00 mark:

https://youtu.be/06CHXEZrY0A?t=657

Love this, btw.

**Comment by mario-deluna** [comment]
I've patched it by turning it into a feature: https://github.com/phpgl/flappyphpant/commit/f97fceb75d492fd9c27a80f11372d180e77ab34b

You probably guessed that I didn't think anyone would ever reach the end. However, the pipes are now infinite! Well, at least until your PHP process dies due to reaching its memory limit.

If you try to go under the map now, the game will become more challenging, and the pipes will actually attempt to crush you.

https://github.com/phpgl/flappyphpant/assets/956212/2c336f2b-23c4-4192-993c-a0f3071f8b8a

Jokes aside, I just watched a replay of your stream on Twitch, and it was incredibly entertaining for me. But also showed me very well where difficulties are in the setup and where more documentation / explanation is required. 

I really appreciated!

And yes, my spelling is, well, unique...
